language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - libconfig8-dev
    - libreadline6-dev
    - libssl-dev
    - liblua5.2-dev
    - lua5.2
    - python-dev
    - python
    - libevent-dev
    - libjansson-dev

script:
  - git submodule update --init --recursive
  - ./configure
  - make
